///////////////////////////////////////////////////////////
//  RoleType.cs
//  Implementation of the Class PartyRoleType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using WoaW.Models.Rules;

namespace WoaW.Models.Parties.Relationship
{
    public class PartyRoleType
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public IEnumerable<PartyRoleConstraint> RoleConstraints { get; set; }
        public IEnumerable<RuleSet> Rules { get; set; }
        public IEnumerable<Responsibility> OptionalResponsibilities { get; set; }
        public IEnumerable<Responsibility> MandatoryResponsibilities { get; set; }

        public PartyRoleType()
        {
            Id = Guid.NewGuid();
            Rules = new List<RuleSet>();
            RoleConstraints = new List<PartyRoleConstraint>();
        }
        public PartyRoleType(string title):this()
        {
            Title = title;
        }

        public void AddRule(RuleSet rule)
        {
            (Rules as List<RuleSet>).Add(rule);
        }
        public void AddConstraint(PartyRoleConstraint constraint)
        {
            (RoleConstraints as List<PartyRoleConstraint>).Add(constraint);
        }

    }//end RoleType   
}
