///////////////////////////////////////////////////////////
//  RelationshipType.cs
//  Implementation of the Class PartyRelationshipType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace WoaW.Models.Parties.Relationship
{
    public class PartyRelationshipType
    {
        private IDictionary<string, PartyRelationship> _relationships;

        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }

        public PartyRelationshipType()
        {
            Id = Guid.NewGuid();
            Constraints = new List<PartyRelationshipConstraint>();
            _relationships = new Dictionary<string, PartyRelationship>();
        }

        public PartyRelationshipType(string title):this()
        {
            Title = title;
        }

        public IEnumerable<PartyRelationshipConstraint> Constraints { get; set; }
        public IDictionary<string, PartyRelationship> Relationship { get { return _relationships; } }

        public void AddConstraint(PartyRelationshipConstraint constraint)
        {
            (Constraints as List<PartyRelationshipConstraint>).Add(constraint);
        }
    }//end RelationshipType  
}
