///////////////////////////////////////////////////////////
//  PartyClasification.cs
//  Implementation of the Class PartyClasification
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace WoaW.Models.Parties.Root
{
    public class PartyClasification
    {
        public System.DateTime FromDate { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime ThruDate { get; set; }
        virtual public PartyType PartyType { get; set; }
        virtual public IEnumerable<Party> Party { get; set; }

        public PartyClasification()
        {
        }

    }//end PartyClasification

}//end namespace Root
