///////////////////////////////////////////////////////////
//  PartyType.cs
//  Implementation of the Class PartyType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Root
{
    public class PartyType
    {
        public string Description { get; set; }
        public System.Guid Id { get; set; }

        public PartyType()
        {
        }

    }//end PartyType

}//end namespace Root

