///////////////////////////////////////////////////////////
//  BornDocument.cs
//  Implementation of the Class BornDocument
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Identifications
{
    public class BornDocument : IdentificationDocument
    {
        public BornDocument()
        {
        }

    }//end BornDocument

}//end namespace Identification