///////////////////////////////////////////////////////////
//  PageScan.cs
//  Implementation of the Class PageScan
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Identifications
{
    public class PageScan
    {
        public System.Guid Id { get; set; }

        public PageScan()
        {
        }

    }//end PageScan

}//end namespace Identification