///////////////////////////////////////////////////////////
//  Signature.cs
//  Implementation of the Class PartySignature
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////


using WoaW.Models.Parties.Root;

namespace WoaW.Models.Parties.Identifications
{
    public class PartySignature
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public int Image { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }

        public PartyIdentifier PartyIdentifier { get; set; }
        public PartyAuthentication Authentication { get; set; }

        public PartySignature()
        {
        }

    }//end Signature

}//end namespace Identification