///////////////////////////////////////////////////////////
//  Pasport.cs
//  Implementation of the Class Passport
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Identifications
{
    public class Passport : IdentificationDocument
    {
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string PasportNum { get; set; }

        public Passport()
        {

        }

    }//end Passport

}//end namespace Identification