///////////////////////////////////////////////////////////
//  Corporation.cs
//  Implementation of the Class Corporation
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class Corporation : LegalOrganization
    {
        public Corporation()
        {
        }

    }//end Corporation

}//end namespace Organizations