///////////////////////////////////////////////////////////
//  Family.cs
//  Implementation of the Class Family
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class Family : InformalOrganization
    {
        public Family()
        {
        }

    }//end Family

}//end namespace Organizations