///////////////////////////////////////////////////////////
//  GovermentAgency.cs
//  Implementation of the Class GovermentAgency
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class GovermentAgency : LegalOrganization
    {
        public GovermentAgency()
        {
        }

    }//end GovermentAgency

}//end namespace Organizations