///////////////////////////////////////////////////////////
//  InformalOrganization.cs
//  Implementation of the Class InformalOrganization
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class InformalOrganization : Organization
    {
        public InformalOrganization()
        {
        }

    }//end InformalOrganization

}//end namespace Organizations