///////////////////////////////////////////////////////////
//  LegalOrganization.cs
//  Implementation of the Class LegalOrganization
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class LegalOrganization : Organization
    {
        public string FederalTaxIdNum { get; set; }

        public LegalOrganization()
        {
        }

    }//end LegalOrganization

}//end namespace Organizations