///////////////////////////////////////////////////////////
//  Team.cs
//  Implementation of the Class Team
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Organizations
{
    public class Team : InformalOrganization
    {
        public Team()
        {
        }

    }//end Team

}//end namespace Organizations