///////////////////////////////////////////////////////////
//  Citizenship.cs
//  Implementation of the Class Citizenship
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using WoaW.Models.Parties.Identifications;
namespace WoaW.Models.Parties.Persons
{
    public class Citizenship
    {
        public string Description { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime ThruDate { get; set; }
        public string Title { get; set; }
        virtual public Country ForCountry { get; set; }
        virtual public Passport Pasport { get; set; }

        public Citizenship()
        {
        }

    }//end Citizenship

}//end namespace Persons