///////////////////////////////////////////////////////////
//  Country.cs
//  Implementation of the Class Country
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class Country
    {
        public System.Guid Id { get; set; }
        public Country()
        {
        }

    }//end Country

}//end namespace Persons