///////////////////////////////////////////////////////////
//  GenderType.cs
//  Implementation of the Class GenderType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class GenderType
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        virtual public GenderCode Code { get; set; }

        public GenderType()
        {
        }

    }//end GenderType

}//end namespace Persons