///////////////////////////////////////////////////////////
//  GenderCode.cs
//  Implementation of the Class GenderCode
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public enum GenderCode:int
    {
        NotKnown=0,
        Male=1,
        Female=2,
        NotApplicable=9,
    }//end GenderCode

}//end namespace Persons