///////////////////////////////////////////////////////////
//  Gender.cs
//  Implementation of the Class Gender
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:04 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class Gender
    {
        public System.Guid Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ThruDate { get; set; }
        virtual public GenderType Type { get; set; }

        public Gender()
        {
        }

    }//end Gender

}//end namespace Persons