///////////////////////////////////////////////////////////
//  MeritalStatusCode.cs
//  Implementation of the Class MeritalStatusCode
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public enum MeritalStatusCode
    {
        NoInfo,
        DomesticPartner,
        Correction,
        Separated,
        Widowed,
        Divorced,
        Single,
        Married

    }//end MeritalStatusCode

}//end namespace Persons