///////////////////////////////////////////////////////////
//  MeritalStatus.cs
//  Implementation of the Class MeritalStatus
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class MeritalStatus
    {
        public System.Guid Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ThruDate { get; set; }
        virtual public MeritalStatusType MeritalStatusType { get; set; }

        public MeritalStatus()
        {
        }

    }//end MeritalStatus

}//end namespace Persons