///////////////////////////////////////////////////////////
//  MeritalStatusType.cs
//  Implementation of the Class MeritalStatusType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class MeritalStatusType
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        virtual public MeritalStatusCode Code { get; set; }

        public MeritalStatusType()
        {
        }

    }//end MeritalStatusType

}//end namespace Persons