///////////////////////////////////////////////////////////
//  PersonNameCode.cs
//  Implementation of the Class PersonNameCode
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public enum PersonNameCode : int
    {
		FirstName,
		NikName,
		MidleName,
		SurName,
		Prefix,
		Sufix

	}//end PersonNameCode

}//end namespace Persons