///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using WoaW.Models.Parties.Root;
using System.Collections.Generic;
using System;

namespace WoaW.Models.Parties.Persons
{
    public class Person : Party
    {
        #region properties

        public DateTime Birthdate { get; set; }
        public string Comment { get; set; }
        public string SSID { get; set; }

        public IEnumerable<MeritalStatus> MeritalStatus { get; set; }
        public IEnumerable<PhisicalCharacteristic> PhisicalCharacteristics { get; set; }
        public IEnumerable<PersonName> Names { get; set; }
        public IEnumerable<Citizenship> Citizenships { get; set; }
        public Gender Gender { get; set; }
        public int Age
        {
            get
            {
                {
                    DateTime now = DateTime.Today;
                    int age = now.Year - Birthdate.Year;
                    if (now < Birthdate.AddYears(age)) age--;

                    if (age < 0)
                        throw new ArgumentOutOfRangeException("Age");
                    return age;
                }
            }
        }

        #endregion

        public Person()
        {
        }
    }

}//end namespace Persons