///////////////////////////////////////////////////////////
//  PersonNameOption.cs
//  Implementation of the Class PersonNameOption
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class PersonNameOption
    {
        public System.Guid Id { get; set; }
        public string Value { get; set; }
        public PersonNameType ForPersonNameType { get; set; }

        public PersonNameOption()
        {
        }

    }//end PersonNameOption

}//end namespace Persons