///////////////////////////////////////////////////////////
//  PersonName.cs
//  Implementation of the Class PersonName
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace WoaW.Models.Parties.Persons
{
    public class PersonName
    {
        public System.Guid Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public int Name { get; set; }
        public System.DateTime ThruDate { get; set; }
        virtual public PersonNameType PersonNameType { get; set; }
        virtual public IEnumerable<PersonNameOption> Options { get; set; }

        public PersonName()
        {
        }

    }//end PersonName

}//end namespace Persons