///////////////////////////////////////////////////////////
//  PhisicalcharacteristicType.cs
//  Implementation of the Class PhisicalcharacteristicType
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace WoaW.Models.Parties.Persons
{
    public class PhisicalcharacteristicType
    {
        public System.Guid Id { get; set; }
        public int Code { get; set; }
        public string Description { get; set; }
        virtual public IEnumerable<PhisicalCharacteristicOption> Options { get; set; }

        public PhisicalcharacteristicType()
        {
        }

    }//end PhisicalcharacteristicType

}//end namespace Persons