///////////////////////////////////////////////////////////
//  PhisicalCharacteristic.cs
//  Implementation of the Class PhisicalCharacteristic
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace WoaW.Models.Parties.Persons
{
    public class PhisicalCharacteristic
    {
        public System.Guid Id { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ThruDate { get; set; }
        public int Value { get; set; }
        virtual public PhisicalcharacteristicType Types { get; set; }
        virtual public IEnumerable<PhisicalCharacteristicOption> Options { get; set; }

        public PhisicalCharacteristic()
        {
        }

    }//end PhisicalCharacteristic

}//end namespace Persons