///////////////////////////////////////////////////////////
//  PhisicalCharacteristicOption.cs
//  Implementation of the Class PhisicalCharacteristicOption
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:06 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.Models.Parties.Persons
{
    public class PhisicalCharacteristicOption
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }

        public PhisicalCharacteristicOption()
        {
        }

    }//end PhisicalCharacteristicOption

}//end namespace Persons